service: resources
variablesResolutionMode: 20210219
frameworkVersion: ">=1.30.0"

custom:
  dotenvVars: ${file(configs.js)}
  accountid: ${self:custom.dotenvVars.AWS_ACCOUNT_ID}
  cloud: ${self:custom.dotenvVars.TARGET_CLOUD}
  region: ${self:custom.dotenvVars.TARGET_REGION}
  preprocessDataBucket: ${self:custom.dotenvVars.TASK_EXEC_PREPROCESS_DATA_BUCKET}
  cacheDataBucket: ${self:custom.dotenvVars.TASK_EXEC_CACHE_DATA_BUCKET}
  logDataBucket: ${self:custom.dotenvVars.TASK_EXEC_LOG_DATA_BUCKET}
  resultDataBucket: ${self:custom.dotenvVars.TASK_EXEC_RESULT_DATA_BUCKET}
  createTaskQueue: ${self:custom.dotenvVars.TASK_EXEC_CREATE_TASK_QUEUE}
  processTaskTriggerQueue: ${self:custom.dotenvVars.TASK_EXEC_PROCESS_TASK_TRIGGER_QUEUE}
  processTaskQueue: ${self:custom.dotenvVars.TASK_EXEC_PROCESS_TASK_QUEUE}
  updateTaskQueue: ${self:custom.dotenvVars.TASK_EXEC_UPDATE_TASK_QUEUE}
  uploadTaskIssuesQueue: ${self:custom.dotenvVars.TASK_EXEC_UPLOAD_TASK_ISSUES_QUEUE}
  generateTaskSummaryQueue: ${self:custom.dotenvVars.TASK_EXEC_GENERATE_TASK_SUMMARY_QUEUE}
  taskTable: ${self:custom.dotenvVars.TASK_EXEC_TASK_TABLE}
  issueTable: ${self:custom.dotenvVars.TASK_EXEC_ISSUE_TABLE}

provider:
  name: aws
  region: ${self:custom.region}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221

resources:
  - ${file(./task-exec-preprocess-data-bucket.yml)}
  - ${file(./task-exec-cache-data-bucket.yml)}
  - ${file(./task-exec-log-data-bucket.yml)}
  - ${file(./task-exec-result-data-bucket.yml)}
  - ${file(./task-exec-queues.yml)}
  - ${file(./task-exec-task-table.yml)}
  - ${file(./task-exec-issue-table.yml)}

