service: task-list-frontend
variablesResolutionMode: 20210219
frameworkVersion: ">=1.30.0"

custom:
  dotenvVars: ${file(configs.js)}
  accountid: ${self:custom.dotenvVars.AWS_ACCOUNT_ID}
  cloud: ${self:custom.dotenvVars.TARGET_CLOUD}
  region: ${self:custom.dotenvVars.TARGET_REGION}
  appsBucket: ${self:custom.dotenvVars.TASK_LIST_APPS_BUCKET}

provider:
  name: aws
  region: ${self:custom.region}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221

resources:
  - ${file(./task-list-apps-bucket.yml)}

