service: task-list-service
variablesResolutionMode: 20210219
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-offline
  - serverless-domain-manager
custom:
  dotenvVars: ${file(configs.js)}
  accountid: ${self:custom.dotenvVars.AWS_ACCOUNT_ID}
  cloud: ${self:custom.dotenvVars.TARGET_CLOUD}
  region: ${self:custom.dotenvVars.TARGET_REGION}
  domain: ${self:custom.dotenvVars.TASK_LIST_DOMAIN}
  taskExecTaskTable: ${self:custom.dotenvVars.TASK_EXEC_TASK_TABLE}
#  userPoolArn: ${env:TASK_LIST_USER_POOL_ARN}
  customDomain:
    domainName: 'tasklistapi.${self:custom.domain}'
    stage: ${self:provider.stage}
    basePath: v1
    certificateName: '*.${self:custom.domain}'
    createRoute53Record: true
    endpointType: regional
  serverless-offline:
    port: 3000

provider:
  name: aws
  region: ${self:custom.region}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  endpointType: regional
  environment:
    TASK_TABLE: '${self:custom.taskExecTaskTable, env:TASK_EXEC_TASK_TABLE}-${self:provider.stage}'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:${self:custom.cloud}:dynamodb:${self:custom.region}:${self:custom.accountid}:*"

functions:
  create:
    handler: handler.create
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-list
    events:
      - http:
          method: POST
          path: tasks
          cors: true
#          authorizer:
#            arn: '${self:custom.userPoolArn}'
  read:
    handler: handler.read
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-list
    events:
      - http:
          method: GET
          path: tasks/{id}
          cors: true
#          authorizer:
#            arn: '${self:custom.userPoolArn}'
  update:
    handler: handler.update
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-list
    events:
      - http:
          method: PUT
          path: tasks/{id}
          cors: true
#          authorizer:
#            arn: '${self:custom.userPoolArn}'
  delete:
    handler: handler.del
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-list
    events:
      - http:
          method: DELETE
          path: tasks/{id}
          cors: true
#          authorizer:
#            arn: '${self:custom.userPoolArn}'
  list:
    handler: handler.list
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-list
    events:
      - http:
          method: GET
          path: tasks
          cors: true
#          authorizer:
#            arn: '${self:custom.userPoolArn}'

